name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */12 * * *"   # Gera a cada 12 horas
  workflow_dispatch:         # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Snake para modo claro
      - name: Generate Snake (Light)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: GuiMillares
          outputs: |
            dist/snake-light.svg

      # Snake para modo escuro
      - name: Generate Snake (Dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: GuiMillares
          color_snake: '#00ff00'
          color_dots: '#444444'
          outputs: |
            dist/snake-dark.svg

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
